# -*- eval: (rp/toggle-export-to-html-async) -*-
#+title: Tehnologii Web 2026
#+author: Petru Rebeja
#+description: Pagina laboratorului Tehnologii Web 2026. Facultatea de Informatică, Universitatea „Alexandru Ioan Cuza” din Iași.
#+language: ro
#+select_tags: export
#+startup: content
#+exclude_tags: noexport
#+options: author:t broken-links:nil c:nil creator:nil
#+options: timestamp:nil title:t toc:t todo:t |:t
#+options: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t ^:{}
#+setupfile: theme-readtheorg.setup
#+html_mathjax: align: left indent: 5em tagside: left font: Neo-Euler

* Orar
:PROPERTIES:
:CUSTOM_ID: orar
:END:

| Zi  | Interval       | Disciplină     | Tip       | Studenți  | Sala |
|-----+----------------+----------------+-----------+-----------+------|
| Joi | 16:00 -- 18:00 | Tehnologii Web | Laborator | InfoRo2A1 | C405 |
| Joi | 18:00 -- 20:00 | Tehnologii Web | Laborator | InfoRo2B4 | C405 |

* Anunțuri
:PROPERTIES:
:CUSTOM_ID: avize
:END:

** Actualizări legate de înscrierea pentru proiect (cont. I)
[2026-04-23 Jo 19:41]

Deoarece au rămas suficient de mute proiecte neatribuite, echipele formate dintr-un singur proiect au fost alocate la proiectele rămase, urmând să fie penalizate conform [[https://edu.info.uaic.ro/web-technologies/web-projects.html#eval][criteriilor de evaluare]].

** Înscrierea pentru proiecte s-a încheiat
[2026-04-13 Lu 09:06]

Înscrierea pentru proiecte s-a încheiat. Echipele înscrise au fost trecute la fiecare [[#proiecte][proiect]]. Înscrierile echipelor =Magdala= și =Salata= au fost invalidate deoarece [[https://edu.info.uaic.ro/web-technologies/web-projects.html][echipa trebuie să fie formată din 2 studenți]].

** Actualizări legate de înscrierea pentru proiecte (cont.)
[2026-04-06 Lu 19:27]

Echipele înscrise până la momentul publicării anunțului au fost trecute la fiecare [[#proiecte][proiect]]. Deoarece proiectul =SoR= a atins pragul maxim de echipe, înscrierile viitoare pentru acest proiect vor fi invalidate.

** Actualizări legate de înscrierea pentru proiecte
[2026-03-30 Lu 19:49]

Echipele înscrise până la momentul publicării anunțului au fost trecute la fiecare [[#proiecte][proiect]]. Înscrierile echipelor =Proiect PIV= și =the boss= au fost invalidate; motivul --- [[https://edu.info.uaic.ro/web-technologies/web-projects.html][echipa trebuie să fie formată din 2 studenți]].

** A început înscrierea pentru proiecte
[2026-03-29 Du 12:53]

În secțiunea [[#proiecte][=Proiecte=]] au fost afișate proiectele propuse și formularul de înscriere. Termen-limită: 12 aprilie 2026, ora 23:59.
Dacă apar erori în afișarea proiectelor, statisticilor sau formularului de înregistrare vă rog să le semnalați pe e-mail.

-----

* Săptămâna 1
:PROPERTIES:
:CUSTOM_ID: s01
:END:

- Aspecte administrative
- Recapitulare curs
- Noțiuni de bază

* Săptămâna 2
:PROPERTIES:
:CUSTOM_ID: s02
:END:

** Recapitulare curs

- arhitectura client-server
- comunicare HTTP

** HTML + CSS

Separarea conținutului de prezentare în paginile HTML.

*** Exercițiu

Creați pagina de contact pentru afacerea proprie; aplicați stiluri CSS pentru a îmbunătăți aspectul paginii.

*Cerințe*:
1. O singură foaie de stil în pagină.
2. Pagina trebuie să includă date (fictive) de contact:
   1. Adresă
   2. Adresă de e-mail
   3. Telefon
   4. Legături la profile de rețele sociale
3. Pagina trebuie să includă un formular (nefuncțional) de contact

* Săptămâna 3
:PROPERTIES:
:CUSTOM_ID: s03
:END:
** Recapitulare curs

- arhitectura client-server
- scripturi CGI

** HTML + CSS

Separarea conținutului de prezentare în paginile HTML.

*** Exercițiu

Creați pagina de contact pentru afacerea proprie folosind /elemente semantice/ în marcajul HTML; aplicați stiluri CSS pentru a îmbunătăți aspectul paginii.

*Cerințe*:
1. O singură foaie de stil în pagină.
2. Pagina trebuie să includă date (fictive) de contact:
   1. Adresă
   2. Adresă de e-mail
   3. Telefon
   4. Legături la profile de rețele sociale
3. Pagina trebuie să includă un formular (nefuncțional) de contact
4. Adăugați următoarele elemente semantice în pagină: =<main>=, =<footer>=, =<section>= și/sau =<article>=.
5. Stilizați pagina astfel încât:
   1. Textul să fie afișat cu un [[https://fonts.google.com/][font Google]]
   2. Dimensiunea semnelor și spațierea liniilor să fie altele decât cele implicite
   3. Datelor de contact să le fie alăturate iconițe [[https://fontawesome.com/][Font Awesome]]

* Săptămâna 4
:PROPERTIES:
:CUSTOM_ID: s04
:END:

** Recapitulare curs

- SDLC
- Arhitectura aplicațiilor Web

** HTML + CSS

- prioritate selectori CSS
- responsive design

*** Exercițiu

Creați pagina de contact pentru afacerea proprie folosind /elemente semantice/ în marcajul HTML; aplicați stiluri CSS pentru a îmbunătăți aspectul paginii și a asigura un design /responsive/.

*Cerințe*:
1. O singură foaie de stil în pagină.
2. Pagina trebuie să includă date (fictive) de contact:
   1. Adresă
   2. Adresă de e-mail
   3. Telefon
   4. Legături la profile de rețele sociale
3. Pagina trebuie să includă un formular (nefuncțional) de contact
4. Adăugați următoarele elemente semantice în pagină: =<main>=, =<footer>=, =<section>= și/sau =<article>=.
5. Stilizați pagina astfel încât:
   1. Textul să fie afișat cu un [[https://fonts.google.com/][font Google]]
   2. Dimensiunea semnelor și spațierea liniilor să fie altele decât cele implicite
   3. Datelor de contact să le fie alăturate iconițe [[https://fontawesome.com/][Font Awesome]]
   4. Pagina să se adapteze automat la dimensiunea dispozitivului de pe care este accesată.

* Săptămâna 5
:PROPERTIES:
:CUSTOM_ID: s05
:END:

** Recapitulare curs

- Introducere în limbajul PHP

** Recapitulare laborator

- Responsive design

*** Exemple

- [[https://quarknerd.com/#css-projects][O colecție de aplicații dezvoltate doar în HTML+CSS]]
- [[https://dev.to/madsstoumann/re-creating-a-pantone-color-deck-in-css-3108][O paletă de culori în CSS]]

*** Exercițiu

Prietenul vostru Gică și-a descoperit recent pasiunea pentru grădinărit și a decis să-și transforme pasiunea într-o afacere. Așa că, după ce și-a umplut pepinera cu diverse plante alese strategic a venit să vă ceară ajutorul în crearea unei pagini Web prin intermediul căreia să își promoveze afacerea. Știind că plantele sunt încă în pepineră și nu are cum să le facă poze, Gică vă roagă ca în primul prototip al paginii să folosiți imagini de pe Internet, dar fiind conștient de problemele care pot apărea din cauza utilizării inadecvate a imaginilor supuse dreptului de autor, Gică insistă ca imaginile pe care le veți utiliza să fie sub licență publică. Totodată, Gică știe că majoritatea utilizatorilor de Internet din ziua de astăzi folosesc mai mult dispozitivele mobile pentru accesarea paginilor Web decât calculatoarele clasice, așa că vă roagă să îi faceți pagina Web astfel încât să poată fi vizualizată de pe mai multe tipuri de dispozitive.

Dat fiind faptul că Gică este un prieten atât de bun, îi săriți imediat în ajutor și începeți să aplicați cunoștințele dobândite la Tehnologii Web pentru a implementa pagina de care are nevoie.

* Săptămâna 6
:PROPERTIES:
:CUSTOM_ID: s06
:END:

** Recapitulare curs

** [[file:e01/][=Hello World!= din PHP și Docker]]

* Săptămâna 7
:PROPERTIES:
:CUSTOM_ID: s07
:END:

** Recapitulare curs

- Dezvoltarea aplicațiilor Web în PHP

** Programare în limbajul PHP

- Continuăm [[file:e01/][exercițiul]] început în laboratorul precedent
- Configurarea mediului de lucru pentru proiecte

-----

* Săptămâna 8
:PROPERTIES:
:CUSTOM_ID: s08
:END:

- Vacanță
- Lucru la proiect

* Săptămâna 9
:PROPERTIES:
:CUSTOM_ID: s09
:END:

- Recapitulare curs
- Discuții asupra proiectelor
- Programare PHP

* Proiecte
:PROPERTIES:
:CUSTOM_ID: proiecte
:END:

** Preambul
:PROPERTIES:
:CUSTOM_ID: preambul
:END:

- Consultați [[https://edu.info.uaic.ro/web-technologies/web-projects.html][cerințele și recomandările]] de pe pagina cursului.
- Alegerea proiectului se face pe principiul primul venit --- primul servit;
- *Termenul-limită pentru înscrieri este 12 aprilie 2026, ora 23:59*.

** Propuneri proiecte
:PROPERTIES:
:CUSTOM_ID: propuneri
:END:

*** =NuW= --- Nuclear Power Plant Web Manager
:PROPERTIES:
:CUSTOM_ID: nuw
:END:

Să se realizeze un sistem Web pentru managementul centralelor nucleare: de la amplasarea optimă a reactoarelor în funcție de eficiență, sol, minimizarea riscurilor și alți factori pana la vizualizarea stării și monitorizarea în timp-real a fiecărui reactor și realizarea de statistici privind gradul de functionalitate, eficiență, pericol, pe baza proceselor atomo-nucleare, condițiile meteo și de uzură (de pildă, oprirea temporara pentru reparatii – planificate sau nu). Se vor genera atat informații numerice, cat și vizualizari sugestive. Starea curentă a centralei nucleare va putea fi consultată și prin intermediul fluxurilor de date RSS. Orice situație de excepție va fi raportata imediat prin e-mail si via notificari direct in navigatorul Web.

**** Echipe

1. M&M International Force (MMIF)
2. NuclearFloppaUni
3. De la Gaze

*** =SOr= --- Soft Drink Web Organizer
:PROPERTIES:
:CUSTOM_ID: sor
:END:

Să se conceapă o aplicație Web care realizeaza managementul preferintelor unei persoane sau grup de persoane în ceea de privește consumul de băuturi non-alcoolice: ceaiuri, lactate, sucuri, siropuri etc. Se va oferi suport și pentru gestiunea (meta-)datelor aferente: categorie, pret, ingrediente, imagini, restricții (e.g., alergeni, regim special), perisabilitate, valabilitate, disponibilitate în funcție de sezon ori regiune geografică, localuri specifice și altele. Sistemul va oferi suport pentru activități de realizare a listelor de cumparaturi, plus administrarea utilizatorilor. Se vor genera statistici diverse ce pot fi exportate în formate deschise, textuale si grafice – minimal, CSV si SVG. Se va realiza, de asemenea, un clasament al celor mai populare produse, disponibil si ca flux de date RSS. Bonus: recurgerea la datele disponibile liber la [[https://world.openfoodfacts.org/category/beverages][Open Food Facts]].

**** Echipe

1. FC Cojeasca
2. Coffee Break
3. DaRiaNa
4. Binary Minds
5. FERIUS
6. Dania
7. Nokia

*** =ReP= --- Resource Web Planner
:PROPERTIES:
:CUSTOM_ID: rep
:END:

Să se dezvolte o aplicație Web care permite gestionarea pe categorii a articolelor esentiale și consumabilelor (e.g., becuri, lemne pentru foc, condimente, toner, cosmetice, pahare de unică folosință, pioneze, medicamente de uz general,...), plus a pieselor de schimb pentru diverse dispozitive – de exemplu, aparate electr(on)ice, automobile, ascensoare etc. – dintr-o gospodărie, organizație sau întreprindere. Instrumentul va fi capabil să notifice, periodic sau la date fixe (eventual, prestabilite), utilizatorul sau un grup de utilizatori în ceea ce privește epuizarea iminentă a unor materiale sau verificarea anumitor echipamente și angrenaje. Aceste notificări vor fi semnalate atât direct în cadrul interfeței aplicației, cât și prin poșta electronică. Se vor oferi posibilități de importare/exportare a datelor în formatele CSV, JSON si XML, iar diversele statistici generate vor putea fi consultate sub forma de documente HTML și PDF.

**** Echipe

1. DLG
2. ProgramareFaina
3. The Two & Twos
4. Șmecherii
5. Padurariu + Stefanache
6. Maris

*** =GiW= --- Gift Web Manager
:PROPERTIES:
:CUSTOM_ID: giw
:END:

Să se conceapă o aplicație Web cu rol de asistent digital oferind sfaturi de alegere a unui cadou – de exemplu, buchet de flori, parfum, joc electronic, articol casnic, abonament la spa – dedicat unei persoane ori grup de persoane, în funcție de preferințe, circumstante (zi de naștere, onomastică, finalizare a studiilor etc.), context (familial, colegial, profesional), buget, ofertant (e.g., doar produsele ce aparțin unui anumit brand), anotimp. Fiecărei categorii de posibile cadouri i se vor atașa proprietăți specifice, inclusiv ingrediente, preț, comentarii, tag-uri asociate, relații cu alte resurse înrudite. De asemenea, se va simula expedierea cadourilor achiziționate la o adresă stabilită, eventual în regim anonim. Administratorul sistemului va avea posibilitatea să consulte rapoarte – generate in formatele HTML, JSON și PDF – privind cadourile recomandate și cele alese efectiv de utilizatori în funcție de categorie, profil al utilizatorilor, o anumită perioada de timp etc.

**** Echipe

1. Powerpuff
2. webEnjoyers

*** =DEW= --- Drug Explorer on Web
:PROPERTIES:
:CUSTOM_ID: dew
:END:

Folosind datele statistice privitoare la [[https://data.gov.ro/organization/agentia-nationala-antidrog][situația drogurilor în România]], să se realizeze un instrument Web de analiză și de vizualizare multicriterială a consumului de droguri pe o perioadă dată, în corelație cu infracțiunile și confiscările efectuate, plus urgențele medicale și campaniile de prevenire a consumului de stupefiante. Căutările multi-criteriale și rapoartele aferente generate vor fi expuse ca documente HTML și in format CSV. Vizualizările generate – minim 3 maniere – vor putea fi exportate în formatele PNG, WebP și SVG.

**** Echipe

1. Walter Pink
2. AA
3. JunkerS
4. Succesul si Bafta

*** =WaT= --- Web Manager for Water Turbines
:PROPERTIES:
:CUSTOM_ID: wat
:END:

Să se dezvolte un sistem Web pentru managementul hidrocentralelor: de la amplasarea optimă a turbinelor hidrocentralei în funcție de eficiență, sol, minimizarea riscurilor și alți factori până la vizualizarea stării și monitorizarea în timp-real a fiecărei turbine. Se vor genera statistici privind gradul de funcționalitate, eficiență, în funcție de debitul de apa, condițiile meteo și de uzură (de pildă, oprire temporară în caz de secetă ori pentru reparații – planificate sau nu). Se vor oferi atât informații numerice, cât și vizualizări sugestive. Starea curentă a centralei va putea fi consultată și prin intermediul fluxurilor de date RSS. Orice situație de excepție va fi raportată imediat prin e-mail și via notificari direct in browser-ul Web.

**** Echipe

1. Salata

*** =MaG= --- Marvel Game
:PROPERTIES:
:CUSTOM_ID: mag
:END:

Pe baza [[https://marvel.fandom.com/wiki/Marvel_Database][datelor despre eroii benzilor desenate Marvel]], să se creeze un joc Web educativ – cu scenariu, niveluri de dificultate, miză și condiții de victorie/înfrângere stabilite de echipă – destinat adolescenților. Clasamentul celor mai buni jucători va fi disponibil via notificări la nivel de navigator Web și ca flux de date RSS. Bonus: implementarea aspectelor precum [[https://www.w3.org/standards/webdesign/i18n][internaționalizarea]] și [[https://www.w3.org/WAI/fundamentals/accessibility-intro/][accesibilitatea]].

**** Echipe

1. Fabian - Stefan

*** =Win= --- Wind Turbine Management on Web
:PROPERTIES:
:CUSTOM_ID: win
:END:

Să se dezvolte un sistem Web pentru managementul centralelor electrice eoliene: de la amplasarea turbinelor eoliene în funcție de eficienta, sol, minimizarea riscului de prăbușire și alți factori pana la vizualizarea stării și monitorizarea în timp-real a fiecărei turbine. Se vor realiza statistici privind gradul de funcționalitate, eficiență, în funcție de condițiile meteo și de uzură (de pildă, oprire temporara pentru reparatii – planificate sau nu). Se vor oferi atât informații numerice, cât și vizualizari sugestive. Starea curentă a centralei va putea fi consultată și prin intermediul fluxurilor de date RSS. Orice situație de excepție va fi raportată imediat prin e-mail și via notificări la nivel de browser Web.

**** Echipe

1. Malin & Edi

*** =PIV= --- PISA Results Visualizer
:PROPERTIES:
:CUSTOM_ID: piv
:END:

Să se implementeze o aplicație Web de vizualizare flexibilă a [[https://www.kaggle.com/datasets/thedevastator/pisa-performance-scores-by-country][datelor referitoare la testul PISA]]. Statisticile și vizualizările generate – minim 3 maniere – vor putea fi exportate în formatele CSV, WebP și SVG. Sistemul va oferi suport și pentru căutarea/filtrarea multi-criterială a datelor, inclusiv comparații între țări, discipline vizate, perioade de timp etc. De considerat și [[https://www.kaggle.com/theworldbank/education-statistics][Education Statistics]]. Bonus: pentru asigurarea performanței, se va include propriul mecanism de /caching/.

**** Echipe

1. Ștrudel de la Lidl
2. ezMelora
3. Proiect PIV
4. Magdala

-----
* Resurse utile
:PROPERTIES:
:CUSTOM_ID: resurse
:END:
1. [[https://www.troyhunt.com/10-commandments-of-good-source-control/][The 10 commandments of good source control management]]
2. [[https://developer.mozilla.org/en-US/docs/Learn][Learn web development | MDN]]
3. [[https://jsfiddle.net/][JSFiddle - Code Playground]]
4. [[https://codewithphp.com/][Learn Modern PHP from First Principles | Code with PHP]]
5. [[https://thecopenhagenbook.com/][The Copenhagen Book]]
6. [[https://github.com/sindresorhus/awesome#contents][Awesome lists about all kinds of interesting topics]]
7. [[https://validator.w3.org/][The W3C Markup Validation Service]]
8. [[https://developer.mozilla.org/en-US/docs/Glossary/Semantics#semantic_elements][Semantic elements in HTML]]
9. [[https://oleg-kantemirov.github.io/cheat-sheet/][CSS selectors and specificity]]
* Date de contact
  :PROPERTIES:
  :CUSTOM_ID: contact
  :END:
** E-mail
:PROPERTIES:
:CUSTOM_ID: e-mail
:END:
   #+begin_src emacs-lisp :exports code
   (concat "petru" "@" "rebeja" ".eu")
   #+end_src
