#+title: Tehnologii Web 2025
#+author: Petru Rebeja
#+description: Pagina laboratorului Tehnologii Web 2025. Facultatea de Informatică, Universitatea „Alexandru Ioan Cuza” din Iași.
#+language: ro
#+select_tags: export
#+startup: content
#+exclude_tags: noexport
#+options: author:t broken-links:nil c:nil creator:nil
#+options: timestamp:nil title:t toc:t todo:t |:t
#+options: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+setupfile: theme-readtheorg.setup
#+html_mathjax: align: left indent: 5em tagside: left font: Neo-Euler

* Săptămâna 1
:PROPERTIES:
:CUSTOM_ID: s01
:END:

- Aspecte administrative
- Recapitulare curs
- Limbajul HTML
- Validarea structurii HTML

* Săptămâna 2
:PROPERTIES:
:CUSTOM_ID: s02
:END:

- Recapitulare curs
- Cascading Style Sheets
- Validarea codului CSS

* Săptămâna 3
:PROPERTIES:
:CUSTOM_ID: s03
:END:

- Recapitulare curs
- Continuăm experimentele cu CSS

* Săptămâna 4
:PROPERTIES:
:CUSTOM_ID: s04
:END:

- Recapitulare curs
- Arhitectura MVC
- CSS

* Săptămâna 5
:PROPERTIES:
:CUSTOM_ID: s05
:END:

- Recapitulare curs
- Recapitulare HTML și CSS
  - [[./e01/][exercițiu]]
  - [[./e01/r/][(o posibilă) rezolvare]]

* Săptămâna 6
:PROPERTIES:
:CUSTOM_ID: s06
:END:

- Recapitulare curs
- [[./e02/][=Hello World!= din PHP și Docker]]

* Săptămâna 7
:PROPERTIES:
:CUSTOM_ID: s07
:END:

- Recapitulare curs
- [[./e03/][Formulare în PHP]]
- Post-Redirect-Get

* Proiecte
:PROPERTIES:
:CUSTOM_ID: proiecte
:END:
** Preambul

- Consultați [[https://edu.info.uaic.ro/web-technologies/web-projects.html][cerințele și recomandările]] de pe pagina cursului.
- Înscrierea echipelor și proiectelor se va face printr-un formular; acesta va fi disponibil începând de sâmbătă, 12 aprilie 2025.
- *Termenul-limită pentru înscrieri este 25 aprilie 2025, ora 23:59*.

** Propuneri proiecte
*** =DeW= --- Device Web Recommender

Realizați o aplicație Web care recomanda utilizatorilor autentificați sau nu diverse dispozitive electronice (telefoane, tablete, ceasuri, drone,...) în funcție de preț ori alte caracteristici – e.g., model similar, facilități, culoare, autonomie etc. Datele analizate vor fi preluate din surse multiple (fluxuri de știri, API-uri disponibile, via scraping) oferite de situri de profil ce vor putea fi precizate de utilizator. Statisticile celor mai populare produse și recomandările generate vor fi disponibile și sub formă de fluxuri de știri RSS. Bonus: functionalitățile principale vor fi oferite de o extensie de navigator Web.

*** =AMa= --- Abbreviation Management

Să se dezvolte o aplicație Web pentru managementul – e.g., explorare, vizualizare, specificare, memorare permanentă – de abrevieri cu semnificații multiple, în diverse limbi. Pe baza facilităților de căutare multi-criterială implementate, utilizatorii autentificați vor putea crea, inventaria și partaja informații despre abrevieri în funcție de diverse caracteristici (limbă, domeniu, dată etc.). Intern, informațiile referitoare la abrevieri vor fi stocate recurgând la [[https://docbook.org/][DocBook]]. Suplimentar, se va oferi suport pentru export (d)in formate precum HTML (e.g., <dt><dd>) și Markdown. Se vor genera statistici diverse ce pot fi exportate în formate deschise – minimal, CSV si PDF. Se va crea, de asemenea, un clasament al celor mai accesate abrevieri, disponibil și ca flux de date RSS.

*** =GoH= --- The Game of SuperHeroes

Pe baza [[https://www.kaggle.com/fivethirtyeight/fivethirtyeight-comic-characters-dataset][datelor despre super-eroi]], să se creeze un joc Web educativ – cu scenariu, niveluri de dificulate, miză și condiții de victorie/înfrângere stabilite de echipă – destinat adolescentilor. Clasamentul celor mai buni jucatori va fi disponibil și ca flux RSS. Este necesară implementarea aspectelor precum [[https://www.w3.org/standards/webdesign/i18n][internaționalizarea]] și [[https://www.w3.org/WAI/fundamentals/accessibility-intro/][accesibilitatea]].

*** =WoW= --- Workout Web Generator

Să se creeze o aplicație Web ce le propune utilizatorilor diverse tipuri de antrenamente privind activități de fizioterapie, kinetoterapie și/sau cu caracter sportiv. Exercițiile fizice gestionate vor fi personalizate în funcție de greutate, înălțime, vârsta, gen, condiție de sănătate și altele. Utilizatorii autentificați vor putea să specifice preferințe pentru antrenamentul dorit: grupe de mușchi, durată, locație (aer liber, acasă) etc, iar aplicația va genera o rutină cu instrucțiuni detaliate, plus exemple foto/video. Sistemul va oferi statistici relevante pentru fiecare utilizator în parte, care vor fi disponibile și ca flux de date RSS. Mai mult, un clasament al celor mai activi utilizatori – conform clasei de vârsta, tipului de antrenament etc. – va fi disponibil public, inclusiv în formatele JSON și PDF.


*** =MeR= --- Media Review Manager

Se dorește crearea unei aplicații Web care permite specificarea adnotărilor textuale și a meta-datelor, plus exprimarea opiniilor vizând conținuturi (multi)media – de exemplu, imagini și/sau video-clipuri – realizate de o persoană sau grup de persoane. Sistemul va realiza managementul acesor conținuturi, inclusiv organizarea lor pe diverse criterii: categorie, an al realizării, legături cu alte resurse înrudite etc. Se vor oferi statistici textuale și grafice exportate în formate deschise – minimal, CSV și SVG, respectiv. Diversele anunțuri (o persoană a comentat un video-clip, a apărut o altă listă de filme de interes, modificarea clasamentului celor mai apreciate imagini ale lunii etc.) vor fi expuse ca flux de știr RSS. Listele de filme preferate vor fi importate/exportate (d)in formate precum JSON și XML. Bonus: recurgerea la un serviciu online (DailyMotion, Vimeo, Instagram, Unsplash).

*** =ReW= --- Resource Web Planner

Să se dezvolte o aplicație Web care permite gestionarea pe categorii a articolelor esențiale și consumabilelor (e.g., becuri, lemne pentru foc, condimente, toner, cosmetice, pahare de unică folosință, pioneze, medicamente de uz general, ...), plus a pieselor de schimb pentru diverse dispozitive -- de exemplu, aparate electr(on)ice, automobile, ascensoare etc. -- dintr-o gospodărie, organizație sau întreprindere. Instrumentul va fi capabil să notifice, periodic sau la date fixe (eventual, prestabilite), utilizatorul sau un grup de utilizatori în ceea ce privește epuizarea iminentă a unor materiale sau verificarea anumitor echipamente și angrenaje. Aceste notificări vor fi semnalate atât direct în cadrul interfeței aplicației, cât și prin poșta electronică. Se vor oferi posibilități de importare/exportare a datelor in formatele CSV, JSON și XML, iar diversele statistici generate vor putea fi consultate sub formă de documente HTML si PDF.

* Întrebări frecvente
:PROPERTIES:
:CUSTOM_ID: faq
:END:

- Avem voie cu documentație/calculator la examen? :: Nu. Examenul va fi unul clasic; veți avea nevoie doar de pix și foi de hârtie.
- Putem propune idei de proiecte proprii? :: Nu.
- Putem folosi =TypeScript= pentru dezvoltarea proiectului? :: Da.
- Putem folosi =Rust= pentru dezvoltarea proiectului? :: Da, dar fără a folosi vreun cadru de lucru (framework).
- Putem folosi =Bootstrap= pentru interfața Web? :: Nu. Deși nu este cadru de lucru, este important să înțelegeți fundamentele pe care biblioteca =Bootstrap= (și altele asemănătoare) le abstractizează.
- Echipele pentru proiect trebuie formate din aceeași grupă? :: Nu neapărat. Echipele pot fi formate din grupele aceluiași profesor.

* Resurse utile
:PROPERTIES:
:CUSTOM_ID: resurse-utile
:END:
- [[https://replit.com/][Replit]]
- [[https://php-fiddle.com/][PHP-fiddle]]
- [[https://jsfiddle.net/][JSFiddle]]
- [[https://formspree.io/][Formspree]]
- [[https://locallhost.me/][localhost.me]]
- [[https://almanac.httparchive.org/en/2024/][Web Almanac 2024]]
- [[https://developer.mozilla.org/en-US/docs/Learn][Learn Web Development | MDN]]
- https://validator.w3.org/
- [[https://www.troyhunt.com/10-commandments-of-good-source-control/][The 10 commandments of good source control management]]

* Date de contact
  :PROPERTIES:
  :CUSTOM_ID: contact
  :END:
** E-mail
:PROPERTIES:
:CUSTOM_ID: e-mail
:END:
   #+begin_src emacs-lisp :exports code
   (concat "petru" "." "rebeja" "@gmail.com")
   #+end_src
